// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7eNv0HHsMCYPcaO1uJzx09yDAjv88tCw',
    appId: '1:726802477000:web:2e6c791b6ec6a384605afd',
    messagingSenderId: '726802477000',
    projectId: 'flutter-e-commerce-b6ceb',
    authDomain: 'flutter-e-commerce-b6ceb.firebaseapp.com',
    storageBucket: 'flutter-e-commerce-b6ceb.firebasestorage.app',
    measurementId: 'G-7MYVBYZLKH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwA9zVDMb6P2v7O8J06hcoLTKVskaVLlw',
    appId: '1:726802477000:android:f7ea05249da95c4e605afd',
    messagingSenderId: '726802477000',
    projectId: 'flutter-e-commerce-b6ceb',
    storageBucket: 'flutter-e-commerce-b6ceb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-5b9bEUFJuz00iKng2XSybDCB4Pfi50M',
    appId: '1:726802477000:ios:43463cc26f10bc71605afd',
    messagingSenderId: '726802477000',
    projectId: 'flutter-e-commerce-b6ceb',
    storageBucket: 'flutter-e-commerce-b6ceb.firebasestorage.app',
    androidClientId: '726802477000-8819i3sfbs1ekndjsnl7ek8s1mlfrpst.apps.googleusercontent.com',
    iosClientId: '726802477000-hq8bc26turad5jvrbeafkh9h9ehfftu8.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterEcommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-5b9bEUFJuz00iKng2XSybDCB4Pfi50M',
    appId: '1:726802477000:ios:43463cc26f10bc71605afd',
    messagingSenderId: '726802477000',
    projectId: 'flutter-e-commerce-b6ceb',
    storageBucket: 'flutter-e-commerce-b6ceb.firebasestorage.app',
    iosBundleId: 'com.example.flutterEcommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7eNv0HHsMCYPcaO1uJzx09yDAjv88tCw',
    appId: '1:726802477000:web:eb13821c03399506605afd',
    messagingSenderId: '726802477000',
    projectId: 'flutter-e-commerce-b6ceb',
    authDomain: 'flutter-e-commerce-b6ceb.firebaseapp.com',
    storageBucket: 'flutter-e-commerce-b6ceb.firebasestorage.app',
    measurementId: 'G-3NGM1B6LPC',
  );
}